name: ci

on:
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*' # don't run ci on tags, should already have run on commit tag points to.
    paths-ignore:
      - README.md # don't run for readme changes.
  pull_request:
    branches:
      - 'dependabot*'
  schedule:
    - cron: '0 0 * * 1' # Every monday at midnight

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test